fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    staging: "https://github.com/nanliu/puppet-staging"
    jenkins: "https://github.com/jenkinsci/puppet-jenkins.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    jenkins_job_builder: "https://github.com/puppet-community/puppet-jenkins_job_builder.git"

  symlinks:
    profile_jenkins: "#{source_dir}"
